### ISSUE TITLE
Major version 3.0.0

### ISSUE THREAD

**Issue by tvbeek** [phpmd/phpmd#1055]
## Description
We are getting more concrete plans for a new major version.

## Tasks for the new major version

- [ ] Drop old PHP versions #1054 
- [ ] Upgrade PDepend to version 3 ( https://github.com/pdepend/pdepend/issues/702 )
- [ ] Clean up syntax where possible .
- [ ] Upgrade used tools.
- [ ] Decide if an upgrade guide is needed or only a release with changelog.
- [ ] Add option to get last V2 phar file from website.
- [ ] Review and merge existing PR's with breaking changes. https://github.com/phpmd/phpmd/pulls?q=is%3Aopen+is%3Apr+milestone%3A3.0.0

## Remove deprecations
- [ ] RuleSetFactory getIgnotePattern -> getIgnorePatterns
- [ ] #746 
- [ ] Other deprecations?

**Comment by ravage84** [comment]
We  set up  some pages for the new major version 3.0 in the repo wiki:

- [3.0-Goals](https://github.com/phpmd/phpmd/wiki/3.0-Goals)
- [3.0-Ideas](https://github.com/phpmd/phpmd/wiki/3.0-Ideas)
- [3.0-Roadmap](https://github.com/phpmd/phpmd/wiki/3.0-Roadmap)

**Comment by llaville** [comment]
At the PHPMD team : is there a date to release the final version 3.0 ? It's a bit long to wait ...

**Comment by AJenbo** [comment]
It's on of my main things to do atm, I'm very much hopin to get it done before wednesday, or at the very least very close to.

**Comment by ToshY** [comment]
> It's on of my main things to do atm, I'm very much hopin to get it done before wednesday, or at the very least very close to.

Hey 👋 Any updates/progress on 3.0?

**Comment by AJenbo** [comment]
It's mostly done with just 12 tasks left to do: https://github.com/phpmd/phpmd/milestone/25

**Comment by AJenbo** [comment]
All work is done now as fare as I can tell, all that's needed now is the team reviewing the 6 pending PRs, agreeing on the state of things and pushing the launch button. If you want to test it out early you can run `composer require phpmd/phpmd dev-3.x-finalize`

**Comment by lussoluca** [comment]
> All work is done now as fare as I can tell, all that's needed now is the team reviewing the 6 pending PRs, agreeing on the state of things and pushing the launch button. If you want to test it out early you can run `composer require phpmd/phpmd dev-3.x-finalize`

Is there something we can do to speed up the process? Thanks!

**Comment by AJenbo** [comment]
i think the last was merged this week. I need to go over the feedback and finalize the pdepend migration guide

**Comment by AJenbo** [comment]
Status on what's missing for 3.0.0:
- Most PRs for addressing feedback has been created
- Write Pdepend migration guide
- Release Pdepend 3.0.0
- Update to Pdepend 3.0.0

That's an estimated 8 PRs with 6 of them already ready for review.
